version: "3.8"

services:
  app:
    image: ghcr.io/P-KIALA/E-Results-20:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
